# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages

env:
  - WARNINGS_ARE_ERRORS=false

addons:
  apt:
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libudunits2-dev
      - libmagick++-dev


matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
#    before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
#    deploy:
#      provider: script
#      script: Rscript -e 'pkgdown::deploy_site_github()'
#      skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
