---
title: "Benchmark"
author: "Klaus Schliep"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: rmarkdown::html_vignette
bibliography: phyloregion.bib
vignette: >
   %\VignetteIndexEntry{phylorregion-intro}
   %\VignetteEngine{knitr::rmarkdown}
   %\usepackage[utf8]{inputenc}   
---

## R Markdown
```{r}
library(ape)
library(phyloregion)
library(betapart)
library(picante)
library(vegan)
library(bench)
library(ggplot2)
library(Matrix)

data(africa)
X_Matrix <- africa$comm

X_matrix <- as.matrix(X_Matrix)
object.size(X_Matrix)
object.size(X_matrix)
dim(X_Matrix)
```

### Beta diversity

For betadiversity there is only a small advantage: 
```{r, beta_diversity, cache=TRUE}
fun_phyloregion <- function(x) as.matrix(beta_diss(x)[[3]])
fun_betapart <- function(x) as.matrix(beta.pair(x)[[3]])
fun_vegan  <- function(x) as.matrix(vegdist(x, binary=TRUE)) 

results <- bench::mark(fun_phyloregion(X_Matrix), fun_betapart(X_matrix), 
                       fun_vegan(X_matrix))
summary(results)
autoplot(results)
```

### Phylogenetic beta diversity
The is a huge difference in memory allocations and running time for the 
phylogenetic beta diversity. 
```{r, phylobeta_diversity, cache=TRUE}
# subset matrix and tree 
X_Matrix <- X_Matrix[1:30, ]
X_Matrix <- X_Matrix[, colSums(X_Matrix)>0]
object.size(X_Matrix)
object.size(X_matrix)

tree <- africa$phylo
tree <- keep.tip(tree, colnames(X_Matrix))  
X_matrix <- as.matrix(X_Matrix)

fun_phyloregion <- function(x, tree) 1 - phylobeta(x, tree)[[3]]
fun_picante  <- function(x, tree)phylosor(x, tree)

chk_fun <- function(target, current)
    all.equal(target, current, check.attributes = FALSE)

cmp_betapart <- bench::mark(phylo.beta.pair(X_matrix, tree), 
                        phylobeta(X_Matrix, tree), check=chk_fun)
summary(cmp_betapart)
autoplot(cmp_betapart)

cmp_picante <- bench::mark(phylosor(X_matrix, tree), 
                        fun_phyloregion(X_Matrix, tree), check=chk_fun)
summary(cmp_picante)
autoplot(cmp_picante)
```
Note that the vegan function returns a similarity matrix while the function in 
betapart and phyloregion return a dissimilarity matrix. 

